---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - agentic.clawdlinux.org
  resources:
  - agentcards
  - agentworkloads
  - tenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentic.clawdlinux.org
  resources:
  - agentcards/finalizers
  - agentworkloads/finalizers
  - tenants/finalizers
  verbs:
  - update
- apiGroups:
  - agentic.clawdlinux.org
  resources:
  - agentcards/status
  - agentworkloads/status
  - tenants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - list
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
