apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
type: Opaque
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-credentials" (include "minio.fullname" .))) }}
stringData:
  rootUser: {{ .Values.rootUser | quote }}
  {{- if and $existingSecret $existingSecret.data (index $existingSecret.data "rootPassword") }}
  rootPassword: {{ index $existingSecret.data "rootPassword" | b64dec | quote }}
  {{- else if or (eq .Values.rootPassword "minioadmin") (eq .Values.rootPassword "") }}
  rootPassword: {{ randAlphaNum 32 | quote }}
  {{- else }}
  rootPassword: {{ .Values.rootPassword | quote }}
  {{- end }}
