# Writer Agent - Transform research outline into polished prose
# Part of the research-swarm demo pipeline

import json
import logging
import os
from typing import Any, Dict

from fastapi import FastAPI
from pydantic import BaseModel

from agent.base import AgentConfig, HTTPAgent

logger = logging.getLogger(__name__)
logging.basicConfig(level=os.getenv("LOG_LEVEL", "INFO"))

# Configuration
config = AgentConfig(
    role=os.getenv("AGENT_ROLE", "writer"),
    tone=os.getenv("AGENT_TONE", "engaging_professional"),
    litellm_proxy_url=os.getenv("LITELLM_PROXY_URL", "http://localhost:8000"),
    litellm_key=os.getenv("LITELLM_KEY", "sk-writer-virtual"),
    minio_endpoint=os.getenv("MINIO_ENDPOINT", "http://localhost:9000"),
    minio_bucket=os.getenv("MINIO_BUCKET", "agentic-demo"),
    postgres_url=os.getenv("POSTGRES_URL", "postgresql://spans:spans_dev@localhost:5432/spans"),
)

agent = HTTPAgent(config)
app = agent.app


# Request/Response models
class WriteRequest(BaseModel):
    outline: Dict[str, Any]
    minio_path: str
    span_id: str = None


class WriteResponse(BaseModel):
    draft: str  # Markdown content
    word_count: int
    minio_path: str
    spend: Dict[str, float]


# Main write endpoint
@app.post("/write", response_model=WriteResponse)
async def write(request: WriteRequest) -> WriteResponse:
    """
    Transform research outline into polished prose.
    
    Steps:
    1. Prepare system prompt with tone instructions
    2. Call LLM to write markdown article from outline
    3. Count words in output
    4. Store draft to MinIO
    5. Return draft + metadata
    """
    span_id = request.span_id or agent.create_trace_event("write")["span_id"]
    logger.info(f"Starting write phase (span={span_id})")

    try:
        # Prepare the outline for the LLM
        outline_str = json.dumps(request.outline, indent=2)

        # Step 1 & 2: Create writing prompt and call LLM
        system_prompt = f"""You are an {config.tone} technical writer. 
Your task is to transform a research outline into a well-structured, engaging markdown article.
- Use clear, professional language
- Include transitions between sections
- Add compelling examples where appropriate
- Structure with markdown headers (## Section, ### Subsection)
- Keep paragraphs focused and digestible"""

        user_message = f"""Transform this research outline into a polished markdown article:

{outline_str}

Requirements:
- Minimum 800 words
- Clear structure with headers
- Professional tone
- Include introduction and conclusion
- Use bullet points for complex information"""

        logger.info("Calling LLM to generate article draft")
        llm_response = await agent.call_llm(system_prompt, user_message, temperature=0.8)

        # Extract the generated text
        try:
            draft = llm_response["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError):
            draft = "# Research Article\n\nArticle content would be generated by the LLM.\n\n(Fallback text due to LLM response parsing issue)"

        logger.info(f"Generated draft ({len(draft)} chars)")

        # Step 3: Count words
        word_count = len(draft.split())
        logger.info(f"Word count: {word_count}")

        # Step 4: Mock MinIO storage
        minio_path = f"demo-artifacts/{span_id}/draft.md"
        logger.info(f"Would store draft to MinIO at: {minio_path}")

        # Step 5: Query spend
        spend = await agent.query_spend()
        logger.info(f"Write phase complete. Spend: ${spend.get('total_cost_usd', 0):.6f}")

        return WriteResponse(
            draft=draft,
            word_count=word_count,
            minio_path=minio_path,
            spend=spend,
        )

    except Exception as e:
        logger.error(f"Write phase failed: {e}", exc_info=True)
        raise


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8080)
